# Generated by Django 4.2.16 on 2024-11-23 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0003_alter_post_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="imageProfil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Draft", "Draft"),
                    ("Disabled", "Disabled"),
                ],
                default="Active",
                max_length=100,
            ),
        ),
    ]
