# Generated by Django 4.2.16 on 2024-11-23 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_post_imageprofil_alter_post_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="imageProfil",
        ),
    ]
