# Generated by Django 4.2.16 on 2024-11-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0018_alter_post_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="Profile",
            new_name="profile",
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Active", "Active"),
                    ("Disabled", "Disabled"),
                ],
                default="Active",
                max_length=100,
            ),
        ),
    ]
