# Generated by Django 4.2.16 on 2024-11-26 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0019_rename_profile_post_profile_alter_post_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="image"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Disabled", "Disabled"),
                    ("Active", "Active"),
                ],
                default="Active",
                max_length=100,
            ),
        ),
    ]
