# Generated by Django 4.2.16 on 2024-12-03 23:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0029_alter_post_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
    ]
