# Generated by Django 4.2.16 on 2024-11-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userProfile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.FileField(
                blank=True,
                default="media/image/iconoPerfil.jpg",
                null=True,
                upload_to="image",
            ),
        ),
    ]
